from __future__ import annotations

from copy import deepcopy


DOMAIN_BLOCKS = {
    "executive": [
        {"type": "kpi", "title": "Score geral", "metric": "score_geral", "format": "number"},
        {"type": "kpi", "title": "Cobertura MCCP", "metric": "pct_cobertura_mccp", "format": "percent"},
        {"type": "chart", "title": "Evolucao mensal", "chart": "monthly_visits"},
        {"type": "chart", "title": "Mix de canais", "chart": "top_channels"},
        {"type": "table", "title": "Ranking de consultores", "table": "consultor_ranking"},
        {"type": "table", "title": "Top oportunidades", "table": "opportunity_doctors"},
        {"type": "insight", "title": "Insight automatico", "insight": "executive"},
        {"type": "methodology", "title": "Metodologia", "domain": "executive"},
    ],
    "performance": [
        {"type": "kpi", "title": "Visitas totais", "metric": "visitas_total", "format": "integer"},
        {"type": "kpi", "title": "Visitas por dia", "metric": "visitas_por_dia", "format": "number"},
        {"type": "chart", "title": "Evolucao de visitas", "chart": "monthly_visits"},
        {"type": "chart", "title": "Top consultores", "chart": "ranking_scores"},
        {"type": "table", "title": "Ranking de produtividade", "table": "consultor_productivity"},
        {"type": "table", "title": "Detalhe por consultor", "table": "consultor_ranking"},
        {"type": "insight", "title": "Leitura operacional", "insight": "performance"},
        {"type": "methodology", "title": "Metodologia", "domain": "performance"},
    ],
    "coverage": [
        {"type": "kpi", "title": "Cobertura F2F", "metric": "pct_cobertura_f2f", "format": "percent"},
        {"type": "kpi", "title": "Cobertura multicanal", "metric": "pct_cobertura_multi", "format": "percent"},
        {"type": "chart", "title": "Distribuicao de cobertura", "chart": "coverage_distribution"},
        {"type": "chart", "title": "Evolucao mensal", "chart": "monthly_visits"},
        {"type": "table", "title": "Ranking de cobertura", "table": "consultor_coverage"},
        {"type": "table", "title": "Medicos sem cobertura", "table": "opportunity_doctors"},
        {"type": "insight", "title": "Priorizacao", "insight": "coverage"},
        {"type": "methodology", "title": "Metodologia", "domain": "coverage"},
    ],
    "visitation": [
        {"type": "kpi", "title": "Dias com visita", "metric": "dias_com_visita", "format": "integer"},
        {"type": "kpi", "title": "Medicos visitados", "metric": "medicos_visitados", "format": "integer"},
        {"type": "chart", "title": "Ritmo mensal", "chart": "monthly_visits"},
        {"type": "chart", "title": "Mix de canais", "chart": "top_channels"},
        {"type": "table", "title": "Consultores por cadencia", "table": "consultor_productivity"},
        {"type": "table", "title": "Amostra de visitas", "table": "visit_sample"},
        {"type": "insight", "title": "Consistencia", "insight": "visitation"},
        {"type": "methodology", "title": "Metodologia", "domain": "visitation"},
    ],
    "territory": [
        {"type": "kpi", "title": "Score territorial", "metric": "score_territorial", "format": "number"},
        {"type": "kpi", "title": "UFs visitadas", "metric": "ufs_visitadas", "format": "integer"},
        {"type": "chart", "title": "Amplitude territorial", "chart": "territory_distribution"},
        {"type": "chart", "title": "Ranking territorial", "chart": "territory_scores"},
        {"type": "table", "title": "Detalhe territorial", "table": "consultor_territory"},
        {"type": "table", "title": "Ranking de consultores", "table": "consultor_ranking"},
        {"type": "insight", "title": "Carga territorial", "insight": "territory"},
        {"type": "methodology", "title": "Metodologia", "domain": "territory"},
    ],
    "absence": [
        {"type": "kpi", "title": "Dias de ausencia", "metric": "dias_ausencia", "format": "integer"},
        {"type": "kpi", "title": "% ausencia", "metric": "pct_ausencia", "format": "percent"},
        {"type": "chart", "title": "Ausencia por consultor", "chart": "absence_distribution"},
        {"type": "chart", "title": "Evolucao de visitas", "chart": "monthly_visits"},
        {"type": "table", "title": "Ranking de capacidade", "table": "consultor_capacity"},
        {"type": "table", "title": "Amostra de ausencias", "table": "absence_sample"},
        {"type": "insight", "title": "Capacidade", "insight": "absence"},
        {"type": "methodology", "title": "Metodologia", "domain": "absence"},
    ],
    "specialty": [
        {"type": "kpi", "title": "Especialidades mapeadas", "metric": "specialty_count", "format": "integer"},
        {"type": "kpi", "title": "Cobertura por franquia", "metric": "pct_cobertura_multi", "format": "percent"},
        {"type": "chart", "title": "Top especialidades", "chart": "top_specialties"},
        {"type": "chart", "title": "Especialidade x franquia", "chart": "specialty_franchise"},
        {"type": "table", "title": "Matriz especialidade x franquia", "table": "specialty_franchise"},
        {"type": "table", "title": "Medicos prioritarios", "table": "opportunity_doctors"},
        {"type": "insight", "title": "Gap estrategico", "insight": "specialty"},
        {"type": "methodology", "title": "Metodologia", "domain": "specialty"},
    ],
    "quality": [
        {"type": "kpi", "title": "Score geral", "metric": "score_geral", "format": "number"},
        {"type": "kpi", "title": "Visitas F2F", "metric": "visitas_f2f", "format": "integer"},
        {"type": "chart", "title": "Qualidade por consultor", "chart": "ranking_scores"},
        {"type": "chart", "title": "Cobertura por consultor", "chart": "coverage_distribution"},
        {"type": "table", "title": "Ranking de execucao", "table": "consultor_ranking"},
        {"type": "table", "title": "Amostra de painel", "table": "panel_sample"},
        {"type": "insight", "title": "Qualidade da execucao", "insight": "quality"},
        {"type": "methodology", "title": "Metodologia", "domain": "quality"},
    ],
    "overlap": [
        {"type": "kpi", "title": "Pares com overlap", "metric": "pares_com_overlap", "format": "integer"},
        {"type": "kpi", "title": "Medicos compartilhados", "metric": "medicos_compartilhados", "format": "integer"},
        {"type": "chart", "title": "Top pares", "chart": "overlap_pairs"},
        {"type": "chart", "title": "Score por consultor", "chart": "ranking_scores"},
        {"type": "table", "title": "Tabela de pares", "table": "overlap_pairs"},
        {"type": "table", "title": "Oportunidades", "table": "opportunity_doctors"},
        {"type": "insight", "title": "Conflitos", "insight": "overlap"},
        {"type": "methodology", "title": "Metodologia", "domain": "overlap"},
    ],
    "simulator": [
        {"type": "kpi", "title": "Capacidade estimada", "metric": "capacidade_disponivel", "format": "integer"},
        {"type": "kpi", "title": "Gap de capacidade", "metric": "gap_capacidade", "format": "integer"},
        {"type": "chart", "title": "Cenario de capacidade", "chart": "capacity_scenario"},
        {"type": "chart", "title": "Score por consultor", "chart": "ranking_scores"},
        {"type": "table", "title": "Simulacao por consultor", "table": "consultor_capacity"},
        {"type": "table", "title": "Plano de cobertura", "table": "consultor_coverage"},
        {"type": "insight", "title": "Recomendacao", "insight": "simulator"},
        {"type": "methodology", "title": "Metodologia", "domain": "simulator"},
    ],
    "opportunities": [
        {"type": "kpi", "title": "Score geral", "metric": "score_geral", "format": "number"},
        {"type": "kpi", "title": "Medicos sem cobertura", "metric": "medicos_sem_cobertura", "format": "integer"},
        {"type": "chart", "title": "Top oportunidades", "chart": "opportunity_distribution"},
        {"type": "chart", "title": "Ranking por score", "chart": "ranking_scores"},
        {"type": "table", "title": "Backlog de acao", "table": "opportunity_doctors"},
        {"type": "table", "title": "Ranking consolidado", "table": "consultor_ranking"},
        {"type": "insight", "title": "Plano de acao", "insight": "opportunities"},
        {"type": "methodology", "title": "Metodologia", "domain": "opportunities"},
    ],
    "governance": [
        {"type": "kpi", "title": "Arquivos carregados", "metric": "files_loaded", "format": "integer"},
        {"type": "kpi", "title": "Warnings", "metric": "warnings_count", "format": "integer"},
        {"type": "chart", "title": "Bases por linhas", "chart": "file_sizes"},
        {"type": "chart", "title": "Top colunas", "chart": "top_columns"},
        {"type": "table", "title": "Catalogo de arquivos", "table": "file_catalog"},
        {"type": "table", "title": "Warnings e auditoria", "table": "audit_summary"},
        {"type": "insight", "title": "Confianca metodologica", "insight": "governance"},
        {"type": "methodology", "title": "Metodologia", "domain": "governance"},
    ],
    "channels": [
        {"type": "kpi", "title": "Visitas F2F", "metric": "visitas_f2f", "format": "integer"},
        {"type": "kpi", "title": "Mix F2F", "metric": "pct_visitas_f2f", "format": "percent"},
        {"type": "chart", "title": "Mix de canais", "chart": "top_channels"},
        {"type": "chart", "title": "Distribuicao de cobertura", "chart": "coverage_distribution"},
        {"type": "table", "title": "Canais por consultor", "table": "consultor_productivity"},
        {"type": "table", "title": "Amostra de visitas", "table": "visit_sample"},
        {"type": "insight", "title": "Qualidade de mix", "insight": "channels"},
        {"type": "methodology", "title": "Metodologia", "domain": "channels"},
    ],
    "master_data": [
        {"type": "kpi", "title": "Medicos no painel", "metric": "medicos_painel", "format": "integer"},
        {"type": "kpi", "title": "Especialidades mapeadas", "metric": "specialty_count", "format": "integer"},
        {"type": "chart", "title": "Top especialidades", "chart": "top_specialties"},
        {"type": "chart", "title": "Bases por linhas", "chart": "file_sizes"},
        {"type": "table", "title": "Amostra de painel", "table": "panel_sample"},
        {"type": "table", "title": "Catalogo de arquivos", "table": "file_catalog"},
        {"type": "insight", "title": "Qualidade cadastral", "insight": "master_data"},
        {"type": "methodology", "title": "Metodologia", "domain": "master_data"},
    ],
    "seasonality": [
        {"type": "kpi", "title": "Visitas totais", "metric": "visitas_total", "format": "integer"},
        {"type": "kpi", "title": "Dias com visita", "metric": "dias_com_visita", "format": "integer"},
        {"type": "chart", "title": "Serie temporal", "chart": "monthly_visits"},
        {"type": "chart", "title": "Top canais", "chart": "top_channels"},
        {"type": "table", "title": "Ranking de consultores", "table": "consultor_productivity"},
        {"type": "table", "title": "Amostra de visitas", "table": "visit_sample"},
        {"type": "insight", "title": "Sazonalidade", "insight": "seasonality"},
        {"type": "methodology", "title": "Metodologia", "domain": "seasonality"},
    ],
}


SECTION_BLUEPRINTS = [
    {
        "id": "executive_overview",
        "title": "Executive Overview",
        "description": "Leitura rapida para lideranca com os principais sinais do negocio.",
        "domain": "executive",
        "decision_supported": "Direcionar prioridades executivas e identificar alertas imediatos.",
        "pages": [
            ("snapshot_executivo", "Snapshot Executivo", "Como o negocio se apresenta agora?"),
            ("alertas_prioritarios", "Alertas Prioritarios", "Quais sinais exigem acao imediata?"),
            ("evolucao_geral", "Evolucao Geral", "Como os principais indicadores evoluiram?"),
            ("resumo_sales_force", "Resumo por Sales Force", "Onde estao as maiores diferencas entre times?"),
            ("resumo_gd", "Resumo por GD", "Quais distritos concentram melhor e pior desempenho?"),
        ],
    },
    {
        "id": "performance_comercial",
        "title": "Performance Comercial",
        "description": "Produtividade, execucao e consistencia de visitas por consultor.",
        "domain": "performance",
        "decision_supported": "Priorizar coaching, redistribuicao e correcoes de produtividade.",
        "pages": [
            ("produtividade_geral", "Produtividade Geral", "O time esta produzindo no ritmo esperado?"),
            ("performance_consultor", "Performance por Consultor", "Quem esta acima ou abaixo do esperado?"),
            ("ranking_alta", "Ranking de Alta Performance", "Quem sao os destaques do periodo?"),
            ("ranking_baixa", "Ranking de Baixa Performance", "Onde concentrar suporte e recuperacao?"),
            ("comparativo_mat", "Comparativo MAT vs Recente", "O que mudou no desempenho recente?"),
        ],
    },
    {
        "id": "cobertura_painel",
        "title": "Cobertura e Painel",
        "description": "Cobertura do painel, MCCP e medicos sem contato.",
        "domain": "coverage",
        "decision_supported": "Definir reforco de cobertura e priorizar medicos descobertos.",
        "pages": [
            ("cobertura_mccp", "Cobertura MCCP", "Estamos cobrindo os HCPs que estao no plano?"),
            ("cobertura_f2f", "Cobertura F2F", "Quais medicos receberam visita presencial?"),
            ("fora_painel", "Fora de Painel", "Quanto do esforco saiu do alvo?"),
            ("turnover_painel", "Turnover de Painel", "O painel esta sendo renovado corretamente?"),
            ("medicos_parados", "Medicos Parados", "Quais medicos relevantes estao sem visita?"),
        ],
    },
    {
        "id": "visitacao_frequencia",
        "title": "Visitacao e Frequencia",
        "description": "Cadencia, consistencia e ritmos de visita.",
        "domain": "visitation",
        "decision_supported": "Ajustar frequencia e estabilizar a rotina de execucao.",
        "pages": [
            ("frequencia_real", "Frequencia Real", "A frequencia real acompanha o desejado?"),
            ("consistencia_mensal", "Consistencia Mensal", "O ritmo se manteve estavel ao longo do tempo?"),
            ("visitas_dia", "Visitas por Dia", "Qual a intensidade da agenda diaria?"),
            ("sazonalidade", "Sazonalidade", "Existe padrao temporal na execucao?"),
            ("medico_frequencia", "Medico x Frequencia", "Quais medicos estao abaixo da frequencia ideal?"),
        ],
    },
    {
        "id": "eficiencia_territorial",
        "title": "Eficiencia Territorial",
        "description": "Amplitude territorial, dispersao e carga geografica.",
        "domain": "territory",
        "decision_supported": "Ajustar desenho territorial e reduzir dispersao improdutiva.",
        "pages": [
            ("perfil_setor", "Perfil de Setor", "O setor esta desenhado de forma eficiente?"),
            ("deslocamento", "Deslocamento", "Quanto da operacao exige deslocamento excessivo?"),
            ("brickagem", "Brickagem", "Quais bricks estao subexplorados?"),
            ("cobertura_geografica", "Cobertura Geografica", "A cobertura geografica esta equilibrada?"),
            ("score_territorio", "Score de Territorio", "Quais territorios combinam escala e foco?"),
        ],
    },
    {
        "id": "ausencias_capacidade",
        "title": "Ausencias e Capacidade",
        "description": "Perda de capacidade, ausencias e impactos operacionais.",
        "domain": "absence",
        "decision_supported": "Antecipar perda de capacidade e redistribuir carga.",
        "pages": [
            ("ausencia_total", "Ausencia Total", "Qual o volume total de ausencias?"),
            ("ausencia_produtiva", "Ausencia Produtiva", "Quanto da capacidade ficou comprometida?"),
            ("ausencia_pessoal", "Ausencia Pessoal", "Existem concentracoes por tipo de ausencia?"),
            ("capacidade_disponivel", "Capacidade Disponivel", "Qual a capacidade liquida restante?"),
            ("sazonalidade_ausencias", "Sazonalidade de Ausencias", "As ausencias seguem algum padrao?"),
        ],
    },
    {
        "id": "especialidades_franquias",
        "title": "Especialidades e Franquias",
        "description": "Camada estrategica para priorizacao clinica por franquia.",
        "domain": "specialty",
        "decision_supported": "Concentrar esforco nas especialidades medicas mais relevantes.",
        "pages": [
            ("visao_geral_especialidades", "Visao Geral Especialidades x Franquias", "O esforco esta nas especialidades certas?"),
            ("matriz_especialidade_franquia", "Matriz Especialidade x Franquia", "Onde existem combinacoes com maior gap?"),
            ("cobertura_estrategica", "Cobertura Estrategica por Franquia", "Os medicos relevantes estao cobertos?"),
            ("gaps_consultor", "Gaps por Consultor / SF / GD", "Quem concentra maior gap estrategico?"),
            ("medicos_prioritarios", "Medicos Prioritarios sem Cobertura", "Quais medicos entram no plano de acao?"),
        ],
    },
    {
        "id": "qualidade_execucao",
        "title": "Qualidade de Execucao",
        "description": "Aderencia ao plano, segmentacao e disciplina operacional.",
        "domain": "quality",
        "decision_supported": "Corrigir mix de execucao e qualidade cadastral.",
        "pages": [
            ("aderencia_plano", "Aderencia ao Plano", "As visitas seguiram o plano esperado?"),
            ("execucao_canal", "Execucao por Canal", "O mix de canais esta coerente?"),
            ("segmentacao", "Segmentacao", "Os segmentos certos receberam foco?"),
            ("especialidade_operacional", "Especialidade Operacional", "A especialidade esta apoiando a execucao?"),
            ("qualidade_cadastro", "Qualidade de Cadastro", "Quais cadastros precisam saneamento?"),
        ],
    },
    {
        "id": "overlap_conflitos",
        "title": "Overlap e Conflitos",
        "description": "Sobreposicao entre consultores, times e territorios.",
        "domain": "overlap",
        "decision_supported": "Reduzir conflitos e redistribuir medicos compartilhados.",
        "pages": [
            ("overlap_intra", "Overlap Intra-Time", "Quais overlaps acontecem dentro do mesmo time?"),
            ("overlap_cross", "Overlap Cross-Team", "Onde ha conflito entre times?"),
            ("medicos_compartilhados", "Medicos Compartilhados", "Quais medicos recebem abordagens cruzadas?"),
            ("conflitos_territorio", "Conflitos de Territorio", "Os conflitos estao ligados ao desenho territorial?"),
            ("redistribuicao", "Oportunidade de Redistribuicao", "Que pares oferecem maior oportunidade de ajuste?"),
        ],
    },
    {
        "id": "simulador_planejamento",
        "title": "Simulador e Planejamento",
        "description": "Transformar diagnostico em cenario futuro e acao.",
        "domain": "simulator",
        "decision_supported": "Projetar capacidade e metas de cobertura.",
        "pages": [
            ("simulador_capacidade", "Simulador de Capacidade", "Qual capacidade futura esta disponivel?"),
            ("perfil_territorial", "Simulador por Perfil Territorial", "Como o territorio afeta a capacidade?"),
            ("planejamento_cobertura", "Planejamento de Cobertura", "Qual cobertura e possivel com a capacidade atual?"),
            ("redistribuicao_painel", "Redistribuicao de Painel", "Como redistribuir painel sem perder foco?"),
            ("cenarios_executivos", "Cenarios Executivos", "Que cenarios priorizar para lideranca?"),
        ],
    },
    {
        "id": "oportunidades_plano_acao",
        "title": "Oportunidades e Plano de Acao",
        "description": "Consolidacao de gaps e prioridades acionaveis.",
        "domain": "opportunities",
        "decision_supported": "Definir backlog unico de oportunidades e planos de acao.",
        "pages": [
            ("oportunidades_prioritarias", "Oportunidades Prioritarias", "Onde agir primeiro?"),
            ("plano_consultor", "Plano de Acao por Consultor", "Que acoes cada consultor deve priorizar?"),
            ("plano_sf_gd", "Plano de Acao por SF / GD", "Quais recortes pedem mobilizacao da lideranca?"),
            ("medicos_ativacao", "Medicos Prioritarios para Ativacao", "Quais medicos exigem acao imediata?"),
            ("backlog_operacional", "Backlog de Correcoes Operacionais", "Quais correcoes sustentam o plano?"),
        ],
    },
    {
        "id": "governanca_auditoria",
        "title": "Governanca e Auditoria",
        "description": "Confianca metodologica, fontes, exclusoes e qualidade de dados.",
        "domain": "governance",
        "decision_supported": "Dar rastreabilidade e auditabilidade para o portal.",
        "pages": [
            ("fontes_dados", "Fontes de Dados", "Quais arquivos alimentaram o portal?"),
            ("regras_exclusao", "Regras de Exclusao", "Quais cortes metodologicos precisam ser auditados?"),
            ("deduplicacao", "Deduplicacao", "Quanto foi removido ou consolidado?"),
            ("metodologia_indicadores", "Metodologia dos Indicadores", "Como os indicadores sao calculados?"),
            ("qualidade_completude", "Qualidade e Completude", "Quais lacunas de dado permanecem?"),
        ],
    },
    {
        "id": "canais_mix_omnichannel",
        "title": "Canais e Mix Omnichannel",
        "description": "Leitura do mix de execucao entre F2F e demais canais.",
        "domain": "channels",
        "decision_supported": "Balancear cobertura, produtividade e tipo de interacao.",
        "pages": [
            ("mix_canais", "Mix de Canais", "Qual o peso de cada canal no esforco comercial?"),
            ("cobertura_multicanal", "Cobertura Multicanal", "O mix melhora a cobertura?"),
            ("qualidade_mix", "Qualidade do Mix", "O canal usado faz sentido para o alvo?"),
            ("f2f_prioritario", "F2F Prioritario", "Onde o presencial ainda e decisivo?"),
            ("consistencia_canais", "Consistencia por Canal", "O uso dos canais e consistente no tempo?"),
        ],
    },
    {
        "id": "cadastro_master_data",
        "title": "Cadastro e Master Data",
        "description": "Qualidade estrutural de cadastro, especialidades e atributos mestre.",
        "domain": "master_data",
        "decision_supported": "Saneamento cadastral e melhoria da base de referencia.",
        "pages": [
            ("qualidade_hcp", "Qualidade de HCP", "Os medicos estao bem identificados?"),
            ("qualidade_especialidade", "Qualidade de Especialidade", "As especialidades estao consistentes?"),
            ("qualidade_franquia", "Qualidade de Franquia", "O mapeamento de franquia esta confiavel?"),
            ("anomalias_cadastro", "Anomalias Cadastrais", "Quais cadastros parecem inconsistentes?"),
            ("saneamento_prioritario", "Saneamento Prioritario", "Qual backlog de saneamento deve vir primeiro?"),
        ],
    },
    {
        "id": "tendencias_sazonalidade",
        "title": "Tendencias e Sazonalidade",
        "description": "Evolucao temporal e leitura de tendencia da operacao.",
        "domain": "seasonality",
        "decision_supported": "Separar comportamento estrutural de ruido temporal.",
        "pages": [
            ("serie_geral", "Serie Geral", "Como a execucao evoluiu ao longo do tempo?"),
            ("picos_vales", "Picos e Vales", "Onde houve aceleracao ou desaceleracao relevante?"),
            ("janela_recente", "Janela Recente", "O recorte recente mudou a leitura do negocio?"),
            ("sazonalidade_time", "Sazonalidade por Time", "Os times seguem padroes diferentes?"),
            ("sazonalidade_territorio", "Sazonalidade por Territorio", "O territorio altera a sazonalidade?"),
        ],
    },
]


def build_page_registry() -> dict:
    sections = []
    pages = {}

    for section in SECTION_BLUEPRINTS:
        section_pages = []
        for page_slug, page_title, question in section["pages"]:
            page_id = f"{section['id']}__{page_slug}"
            page = {
                "pageId": page_id,
                "sectionId": section["id"],
                "section": section["title"],
                "subsection": page_title,
                "title": page_title,
                "businessQuestion": question,
                "decisionSupported": section["decision_supported"],
                "domain": section["domain"],
                "blocks": deepcopy(DOMAIN_BLOCKS[section["domain"]]),
            }
            pages[page_id] = page
            section_pages.append(
                {
                    "pageId": page_id,
                    "title": page_title,
                    "businessQuestion": question,
                }
            )
        sections.append(
            {
                "id": section["id"],
                "title": section["title"],
                "description": section["description"],
                "domain": section["domain"],
                "pages": section_pages,
            }
        )

    return {
        "sections": sections,
        "pages": pages,
    }
